"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import "../workspace.css";

const templates = [
  ["CAT6 cable", "Copper type, length, jacket, test standard", "100", "boxes"],
  ["CNC machine", "Working area, spindle, power, warranty", "1", "unit"],
  ["3D printer", "Build volume, materials, training, service", "2", "units"],
  ["Custom product", "Upload a specification or describe the outcome", "", "units"],
] as const;
const sources = ["Alibaba", "Made-in-China", "Global Sources", "IndiaMART", "Direct factory sites", "Google / Bing"];

export default function SourcingWorkspace() {
  const [product, setProduct] = useState(""); const [quantity, setQuantity] = useState(""); const [unit, setUnit] = useState("units");
  const [selectedSources, setSelectedSources] = useState(sources.slice(0, 4)); const [ready, setReady] = useState(false); const [advanced, setAdvanced] = useState(false);
  const [incoterm, setIncoterm] = useState("FOB"); const [currency, setCurrency] = useState("USD"); const [maxLead, setMaxLead] = useState(""); const [verifiedOnly, setVerifiedOnly] = useState(true);
  const canPrepare = product.trim().length >= 3 && Number(quantity) > 0 && selectedSources.length > 0; const sourceSummary = useMemo(() => selectedSources.join(", "), [selectedSources]);
  const toggle = (source: string) => { setSelectedSources((current) => current.includes(source) ? current.filter((item) => item !== source) : [...current, source]); setReady(false); };
  return <main className="shell workspace">
    <header className="topbar"><div><Link className="backLink" href="/">← Command center</Link><p className="eyebrow">INA SMART · FAST SOURCING</p><h1>Build a sourcing brief</h1><p className="muted">Choose a template, channels, and comparison rules before the agent searches.</p></div><span className="pill">Draft workspace</span></header>
    <section className="card templateCard"><div className="sectionHead"><div><h2>Quick-start templates</h2><p className="muted">Pre-fill the fields you use most often.</p></div></div><div className="templateGrid">{templates.map(([name, detail, amount, templateUnit]) => <button className="template" key={name} onClick={() => { setProduct(name); setQuantity(amount); setUnit(templateUnit); setReady(false); }}><strong>{name}</strong><span>{detail}</span></button>)}</div></section>
    <div className="workspaceGrid"><section className="card formCard"><div className="sectionHead"><div><h2>What do you need?</h2><p className="muted">Minimum information for a precise search.</p></div><span className="step">1 / 3</span></div><label>Product or project<input value={product} onChange={(e) => { setProduct(e.target.value); setReady(false); }} placeholder="e.g. CAT6 U/UTP 305m solid bare copper" autoFocus /></label><div className="formRow"><label>Quantity<input type="number" min="1" value={quantity} onChange={(e) => { setQuantity(e.target.value); setReady(false); }} placeholder="500" /></label><label>Unit<select value={unit} onChange={(e) => setUnit(e.target.value)}><option>units</option><option>boxes</option><option>sets</option><option>kg</option><option>m</option></select></label></div><div className="formRow"><label>Destination<input defaultValue="Doha, Qatar" /></label><label>Currency<select value={currency} onChange={(e) => setCurrency(e.target.value)}><option>USD</option><option>QAR</option><option>EUR</option><option>CNY</option></select></label></div><label>Technical requirement<textarea rows={5} placeholder="Paste specifications or describe mandatory requirements..." /></label><button className="advancedButton" onClick={() => setAdvanced(!advanced)}>{advanced ? "Hide" : "Show"} advanced filters <span>{advanced ? "↑" : "↓"}</span></button>{advanced && <div className="advancedPanel"><label>Maximum lead time (days)<input type="number" min="1" value={maxLead} onChange={(e) => setMaxLead(e.target.value)} placeholder="45" /></label><label>Requested Incoterm<select value={incoterm} onChange={(e) => setIncoterm(e.target.value)}><option>FOB</option><option>EXW</option><option>CIF</option><option>DDP</option></select></label><label className="check"><input type="checkbox" checked={verifiedOnly} onChange={(e) => setVerifiedOnly(e.target.checked)} /> Prefer verified factories</label></div>}<button className="primary actionButton" disabled={!canPrepare} onClick={() => setReady(true)}>Prepare search brief →</button>{!canPrepare && <p className="formHint">Enter a product, quantity, and at least one source.</p>}</section>
      <aside className="card sourceCard"><div className="sectionHead"><div><h2>Search channels</h2><p className="muted">Select the first places to search.</p></div><span className="step">2 / 3</span></div><div className="sourceList">{sources.map((source) => <label className={`sourceOption ${selectedSources.includes(source) ? "selected" : ""}`} key={source}><input type="checkbox" checked={selectedSources.includes(source)} onChange={() => toggle(source)} /><span><strong>{source}</strong><small>{source === "Direct factory sites" ? "Official evidence and contact" : source === "Google / Bing" ? "Broader discovery" : "Marketplace supplier profiles"}</small></span></label>)}</div><div className="sourceNote"><strong>Credentials stay separate</strong><p className="muted">Public discovery needs no password. Connect marketplace accounts only when messaging is approved.</p></div></aside></div>
    <section className={`card briefCard ${ready ? "ready" : ""}`}><div className="sectionHead"><div><h2>Search plan</h2><p className="muted">Review the deterministic search basis before provider calls.</p></div><span className="step">3 / 3</span></div>{ready ? <div className="briefSummary"><div><span>Request</span><strong>{quantity} {unit} · {product}</strong></div><div><span>Sources</span><strong>{sourceSummary}</strong></div><div><span>Basis</span><strong>{currency} · {incoterm}{maxLead ? ` · ≤ ${maxLead} days` : ""}</strong></div><p className="successText">Brief ready. The authenticated runner will use these constraints, deduplicate evidence, and keep incompatible offers separate.</p></div> : <div className="emptyBox">Complete the product, quantity, and source selection to preview the search plan.</div>}</section>
  </main>;
}
